[project]
name = "interlinked"
description = """
Interlinked provides routing, dependency management and dependency
injection for data-driven applications
"""
version = "0.2"

[tool.setuptools]
packages = ["interlinked"]
